# Generated by Django 5.2 on 2025-05-01 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя клиента')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия клиента')),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество клиента')),
                ('phone', models.CharField(max_length=100, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название транспортного средства')),
                ('vehicle_type', models.CharField(choices=[('car', 'Машина'), ('truck', 'Грузовик'), ('motorcycle', 'Мотоцикл')], max_length=20, verbose_name='Тип транспортного средства')),
                ('gos_number', models.CharField(max_length=20, unique=True, verbose_name='Гос. номер')),
            ],
            options={
                'verbose_name': 'Транспортное средство',
                'verbose_name_plural': 'Транспортные средства',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название заказа')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес доставки')),
                ('order_coast', models.FloatField(verbose_name='Сумма заказа')),
                ('delivery_coast', models.FloatField(verbose_name='Стоимость доставки')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заказа')),
                ('order_status', models.CharField(choices=[('new', 'Новый заказ'), ('in_process', 'В процессе доставки'), ('delivered', 'Доставлено')], default='new', max_length=20, verbose_name='Статус заказа')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя курьера')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия курьера')),
                ('phone', models.CharField(max_length=100, verbose_name='Телефон')),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.vehicle', verbose_name='Транспортное средство')),
            ],
            options={
                'verbose_name': 'Курьер',
                'verbose_name_plural': 'Курьеры',
            },
        ),
    ]
